[package]
name = "uart_json"
version = "0.1.0"
edition = "2021"

[dependencies]
derefable = "0.1.0"
lazy_static = "1.4.0"
wokwi_chip_ll = "0.1"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
